<?php
declare(strict_types=1);
require __DIR__.'/config/bootstrap.php';
$user=require_auth();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='create_project'){check_csrf();$name=trim($_POST['name']??'');$description=trim($_POST['description']??'');if($name==='')$error='Введите название проекта.';else{$s=$pdo->prepare('INSERT INTO projects(user_id,name,description) VALUES(?,?,?)');$s->execute([$user['id'],$name,$description?:null]);redirect('project.php?id='.$pdo->lastInsertId());}}
$s=$pdo->prepare('SELECT p.*,COALESCE((SELECT SUM(i.quantity*i.price) FROM estimate_items i JOIN estimate_categories c ON c.id=i.category_id WHERE c.project_id=p.id),0) total FROM projects p WHERE p.user_id=? ORDER BY p.updated_at DESC');$s->execute([$user['id']]);$projects=$s->fetchAll();
$pageTitle='Проекты';require __DIR__.'/includes/header.php';?>
<div class="app-page"><div class="container"><div class="page-head"><div><div class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</div><h1>Мои проекты</h1><p class="text-muted mb-0">Создавайте и редактируйте строительные сметы.</p></div><button class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#newProject">+ Новый проект</button></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="row g-4"><?php foreach($projects as $p):?><div class="col-md-6 col-xl-4"><a class="project-card surface" href="project.php?id=<?=$p['id']?>"><div class="project-top"><span class="status-dot"></span><span>В работе</span></div><h3><?=e($p['name'])?></h3><p><?=e($p['description']?:'Без описания')?></p><div class="project-bottom"><span>Итого</span><strong><?=number_format((float)$p['total'],2,',',' ')?> ₽</strong></div></a></div><?php endforeach;?><?php if(!$projects):?><div class="col-12"><div class="empty-state surface"><div class="feature-icon">+</div><h3>Первый проект</h3><p>Создайте проект и добавьте первую позицию в смету.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newProject">Создать проект</button></div></div><?php endif;?></div></div></div>
<div class="modal fade" id="newProject" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Новый проект</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_project"><label class="form-label">Название</label><input class="form-control form-control-lg mb-3" name="name" required placeholder="Например, Дом на Курортной"><label class="form-label">Описание</label><textarea class="form-control" name="description" rows="3"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Создать</button></div></form></div></div></div>
<?php require __DIR__.'/includes/footer.php';?>