<?php
declare(strict_types=1);
require __DIR__.'/config/bootstrap.php';
$user=require_auth();$id=(int)($_GET['id']??0);
$q=$pdo->prepare("SELECT * FROM projects WHERE id=? AND ownerId=?");$q->execute([$id,$user['id']]);$project=$q->fetch();if(!$project)redirect('dashboard.php');
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();$action=$_POST['action']??'';
 if($action==='category'){ $name=trim($_POST['name']??'');if($name!==''){$q=$pdo->prepare("INSERT INTO estimatecategories(projectId,name,sortOrder) VALUES(?,?,?)");$q->execute([$id,$name,(int)$pdo->query("SELECT COALESCE(MAX(sortOrder),0)+1 FROM estimatecategories WHERE projectId=".(int)$id)->fetchColumn()]);}redirect('project.php?id='.$id);}
 if($action==='item'){ $cat=(int)($_POST['category_id']??0);$q=$pdo->prepare("SELECT id FROM estimatecategories WHERE id=? AND projectId=?");$q->execute([$cat,$id]);if($q->fetch()){ $name=trim($_POST['name']??'');$qty=(float)str_replace(',','.',$_POST['quantity']??0);$unit=trim($_POST['unit']??'шт');$price=(float)str_replace(',','.',$_POST['price']??0);if($name!==''){$q=$pdo->prepare("INSERT INTO estimateitems(categoryId,name,quantity,unit,price,source) VALUES(?,?,?,?,?,?)");$q->execute([$cat,$name,$qty,$unit,$price,'manual']);}}redirect('project.php?id='.$id);}
 if($action==='update_item'){ $item=(int)$_POST['item_id'];$q=$pdo->prepare("SELECT i.id FROM estimateitems i JOIN estimatecategories c ON c.id=i.categoryId WHERE i.id=? AND c.projectId=?");$q->execute([$item,$id]);if($q->fetch()){ $name=trim($_POST['name']??'');$qty=(float)str_replace(',','.',$_POST['quantity']??0);$unit=trim($_POST['unit']??'шт');$price=(float)str_replace(',','.',$_POST['price']??0);$q=$pdo->prepare("UPDATE estimateitems SET name=?,quantity=?,unit=?,price=? WHERE id=?");$q->execute([$name,$qty,$unit,$price,$item]);}redirect('project.php?id='.$id);}
 if($action==='delete_item'){ $q=$pdo->prepare("DELETE i FROM estimateitems i JOIN estimatecategories c ON c.id=i.categoryId WHERE i.id=? AND c.projectId=?");$q->execute([(int)$_POST['item_id'],$id]);redirect('project.php?id='.$id);}
 if($action==='delete_category'){ $cat=(int)$_POST['category_id'];$q=$pdo->prepare("DELETE i FROM estimateitems i JOIN estimatecategories c ON c.id=i.categoryId WHERE c.id=? AND c.projectId=?");$q->execute([$cat,$id]);$q=$pdo->prepare("DELETE FROM estimatecategories WHERE id=? AND projectId=?");$q->execute([$cat,$id]);redirect('project.php?id='.$id);}
 if($action==='status'){ $allowed=['draft','in_progress','review','completed','archived'];$st=$_POST['status']??'draft';if(in_array($st,$allowed,true)){$q=$pdo->prepare("UPDATE projects SET status=? WHERE id=? AND ownerId=?");$q->execute([$st,$id,$user['id']]);}redirect('project.php?id='.$id);}
 if($action==='delete_project'){ $q=$pdo->prepare("DELETE FROM projects WHERE id=? AND ownerId=?");$q->execute([$id,$user['id']]);redirect('dashboard.php');}
}
$q=$pdo->prepare("SELECT c.*,COALESCE(SUM(i.quantity*i.price),0) total,COUNT(i.id) item_count FROM estimatecategories c LEFT JOIN estimateitems i ON i.categoryId=c.id WHERE c.projectId=? GROUP BY c.id ORDER BY c.sortOrder,c.id");$q->execute([$id]);$cats=$q->fetchAll();$total=0;$itemsCount=0;foreach($cats as &$cat){$q=$pdo->prepare("SELECT * FROM estimateitems WHERE categoryId=? ORDER BY id");$q->execute([$cat['id']]);$cat['items']=$q->fetchAll();$total+=(float)$cat['total'];$itemsCount+=(int)$cat['item_count'];}unset($cat);
$label=['draft'=>'Черновик','in_progress'=>'В работе','review'=>'На согласовании','completed'=>'Завершён','archived'=>'Архив'][$project['status']]??$project['status'];
$pageTitle=$project['name'];require __DIR__.'/includes/app_header.php';
?>
<section class="page-wrap">
<div class="estimate-heading"><div><a href="dashboard.php" class="back-button"><i class="bi bi-arrow-left"></i> Все проекты</a><div class="estimate-title-row"><div class="project-symbol"><i class="bi bi-house"></i></div><div><h1><?=e($project['name'])?></h1><p><?=e($project['city'])?> · <?=e($project['clientName'])?> · <?=e($project['workType'])?></p></div></div></div><div class="heading-actions"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="status"><select class="status-select" name="status" onchange="this.form.submit()"><?php foreach(['draft'=>'Черновик','in_progress'=>'В работе','review'=>'На согласовании','completed'=>'Завершён','archived'=>'Архив'] as $v=>$t):?><option value="<?=$v?>" <?=$project['status']===$v?'selected':''?>><?=$t?></option><?php endforeach;?></select></form><a class="primary-button" href="workspace.php?view=documents&id=<?=$id?>"><i class="bi bi-file-earmark-text"></i> Документы</a></div></div>
<div class="estimate-summary"><div><span>ИТОГО ПО СМЕТЕ</span><strong><?=number_format($total,0,',',' ')?> ₽</strong><small><?=number_format($total,2,',',' ')?> ₽ с копейками</small></div><div class="summary-stats"><div><span>РАЗДЕЛОВ</span><b><?=count($cats)?></b></div><div><span>ПОЗИЦИЙ</span><b><?=$itemsCount?></b></div><div><span>СРОК</span><b><?=e($project['deadline']?date('d.m.Y',strtotime($project['deadline'])):'—')?></b></div></div><div class="summary-actions"><a class="outline-button" href="workspace.php?view=scan&id=<?=$id?>"><i class="bi bi-upload"></i> Импорт</a><button class="outline-button" data-bs-toggle="modal" data-bs-target="#categoryModal"><i class="bi bi-plus-lg"></i> Раздел</button></div></div>
<div class="estimate-toolbar"><div class="toolbar-tabs"><a class="active" href="project.php?id=<?=$id?>">Смета <span><?=$itemsCount?></span></a><a href="workspace.php?view=schedule&id=<?=$id?>">График</a><a href="workspace.php?view=team&id=<?=$id?>">Команда</a><a href="workspace.php?view=acceptance&id=<?=$id?>">Приёмка</a></div><a class="text-button" href="workspace.php?view=analytics&id=<?=$id?>">Аналитика <i class="bi bi-arrow-up-right"></i></a></div>
<div class="estimate-list">
<?php foreach($cats as $n=>$cat):?><div class="estimate-group"><div class="group-heading"><span class="group-number"><?=str_pad((string)($n+1),2,'0',STR_PAD_LEFT)?></span><div><h3><?=e($cat['name'])?></h3><span><?=$cat['item_count']?> позиций</span></div><strong><?=number_format((float)$cat['total'],0,',',' ')?> ₽</strong><button class="icon-button" title="Удалить раздел" onclick="if(confirm('Удалить раздел и его позиции?'))document.getElementById('delcat<?=$cat['id']?>').submit()"><i class="bi bi-three-dots"></i></button></div>
<div class="estimate-table"><div class="table-head"><span>Наименование</span><span>Кол-во</span><span>Ед.</span><span>Цена</span><span>Сумма</span><span></span></div>
<?php foreach($cat['items'] as $item):$sum=(float)$item['quantity']*(float)$item['price'];?><div class="table-row"><div class="work-name"><i class="work-dot"></i><?=e($item['name'])?></div><span><?=rtrim(rtrim(number_format((float)$item['quantity'],3,',',' '),'0'),',')?></span><span><?=e($item['unit'])?></span><span><?=number_format((float)$item['price'],2,',',' ')?> ₽</span><strong><?=number_format($sum,2,',',' ')?> ₽</strong><div class="row-actions"><button type="button" title="Редактировать" onclick="editRow(<?=$item['id']?>)"><i class="bi bi-pencil"></i></button><form id="edit<?=$item['id']?>" method="post" style="display:none"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update_item"><input type="hidden" name="item_id" value="<?=$item['id']?>"><input name="name" value="<?=e($item['name'])?>"><input name="quantity" value="<?=e((string)$item['quantity'])?>"><input name="unit" value="<?=e($item['unit'])?>"><input name="price" value="<?=e((string)$item['price'])?>"></form><button type="button" title="Удалить" onclick="if(confirm('Удалить позицию?'))document.getElementById('delete<?=$item['id']?>').submit()"><i class="bi bi-trash3"></i></button><form id="delete<?=$item['id']?>" method="post" style="display:none"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_item"><input type="hidden" name="item_id" value="<?=$item['id']?>"></form></div></div><?php endforeach;?>
<button class="add-row" data-bs-toggle="modal" data-bs-target="#item<?=$cat['id']?>"><i class="bi bi-plus-lg"></i> Добавить позицию</button></div></div>
<form id="delcat<?=$cat['id']?>" method="post" style="display:none"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_category"><input type="hidden" name="category_id" value="<?=$cat['id']?>"></form>
<div class="modal fade" id="item<?=$cat['id']?>" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Добавить позицию</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="item"><input type="hidden" name="category_id" value="<?=$cat['id']?>"><label class="form-label">Наименование</label><input class="form-control mb-3" name="name" required placeholder="Штукатурка стен по маякам"><div class="form-grid"><div><label class="form-label">Количество</label><input class="form-control" name="quantity" value="1"></div><div><label class="form-label">Единица</label><input class="form-control" name="unit" value="м²"></div><div><label class="form-label">Цена</label><input class="form-control" name="price" value="0"></div></div></div><div class="modal-footer"><button class="outline-button" type="button" data-bs-dismiss="modal">Отмена</button><button class="primary-button">Добавить</button></div></form></div></div></div>
<?php endforeach;?>
<?php if(!$cats):?><div class="empty-state module-panel"><i class="bi bi-list-columns-reverse fs-2 text-primary"></i><h3 class="mt-3">Смета пока пустая</h3><p class="text-muted">Создайте первый раздел и добавьте работы или материалы.</p><button class="primary-button" data-bs-toggle="modal" data-bs-target="#categoryModal">Создать раздел</button></div><?php endif;?>
<div class="estimate-total"><span>Итого по проекту</span><strong><?=number_format($total,2,',',' ')?> ₽</strong></div></div>
<div class="mt-4 d-flex justify-content-between align-items-center"><a class="text-button" href="workspace.php?view=scan&id=<?=$id?>"><i class="bi bi-stars"></i> Смета из файла</a><form method="post" onsubmit="return confirm('Удалить проект и всю смету?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_project"><button class="text-danger border-0 bg-transparent small">Удалить проект</button></form></div>
</section>
<div class="modal fade" id="categoryModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Новый раздел</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="category"><label class="form-label">Название</label><input class="form-control" name="name" required placeholder="Материалы, Работы, Электрика..."></div><div class="modal-footer"><button class="outline-button" type="button" data-bs-dismiss="modal">Отмена</button><button class="primary-button">Создать</button></div></form></div></div></div>
<script>
function editRow(id){const f=document.getElementById('edit'+id);if(!f)return;const row=f.parentElement.closest('.table-row');const n=f.querySelector('[name="name"]').value,q=f.querySelector('[name="quantity"]').value,u=f.querySelector('[name="unit"]').value,p=f.querySelector('[name="price"]').value;row.innerHTML='<div class="work-name"><i class="work-dot"></i><input class="cell-input js-name" value="'+n.replace(/"/g,'&quot;')+'"></div><div><input class="cell-input js-qty" value="'+q+'"></div><div><input class="cell-input js-unit" value="'+u+'"></div><div><input class="cell-input js-price" value="'+p+'"></div><strong>—</strong><div class="row-actions"><button class="save-row" type="button" onclick="saveInline('+id+')"><i class="bi bi-check-lg"></i></button><button class="cancel-row" type="button" onclick="location.reload()"><i class="bi bi-x-lg"></i></button></div>';row.classList.add('is-editing')}
function saveInline(id){const row=document.querySelector('.table-row.is-editing');const f=document.getElementById('edit'+id);f.querySelector('[name="name"]').value=row.querySelector('.js-name').value;f.querySelector('[name="quantity"]').value=row.querySelector('.js-qty').value;f.querySelector('[name="unit"]').value=row.querySelector('.js-unit').value;f.querySelector('[name="price"]').value=row.querySelector('.js-price').value;f.submit()}
</script>
<?php require __DIR__.'/includes/app_footer.php';?>