<?php
declare(strict_types=1);
require __DIR__.'/config/bootstrap.php';
$user=require_auth();
$view=$_GET['view']??'schedule';$projectId=(int)($_GET['id']??0);
$project=null;
if($projectId){$q=$pdo->prepare("SELECT * FROM projects WHERE id=? AND ownerId=?");$q->execute([$projectId,$user['id']]);$project=$q->fetch();if(!$project)redirect('dashboard.php');}
$pdo->exec("CREATE TABLE IF NOT EXISTS smetogram_rooms(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,project_id BIGINT UNSIGNED NULL,name VARCHAR(120) NOT NULL,length_m DECIMAL(10,2) NOT NULL,width_m DECIMAL(10,2) NOT NULL,height_m DECIMAL(10,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(project_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$action=$_POST['action']??'';
 if($action==='add_task'&&$project){$q=$pdo->prepare("INSERT INTO scheduletasks(projectId,title,startsAt,endsAt,status,paymentMilestone) VALUES(?,?,?,?,?,?)");$q->execute([$projectId,trim($_POST['title']),$_POST['startsAt']?:null,$_POST['endsAt']?:null,'planned',(float)$_POST['paymentMilestone']]);}
 if($action==='add_member'&&$project){$role=$_POST['role']??'client';$q=$pdo->prepare("INSERT INTO projectmembers(projectId,invitedEmail,invitedPhone,role,inviteToken) VALUES(?,?,?,?,?)");$q->execute([$projectId,trim($_POST['email'])?:null,trim($_POST['phone'])?:null,$role,bin2hex(random_bytes(12))]);}
 if($action==='add_doc'&&$project){$q=$pdo->prepare("INSERT INTO projectdocuments(projectId,type,title,status) VALUES(?,?,?,?)");$q->execute([$projectId,$_POST['type'],trim($_POST['title']),'draft']);}
 if($action==='send_message'&&$project){$body=trim($_POST['body']??'');if($body!==''){$q=$pdo->prepare("INSERT INTO projectmessages(projectId,authorId,channel,body) VALUES(?,?,?,?,?)");$q->execute([$projectId,$user['id'],$_POST['channel']??'general',$body]);}}
 if($action==='add_stage'&&$project){$q=$pdo->prepare("INSERT INTO acceptancestages(projectId,title,amount,holdback,status) VALUES(?,?,?,?,?)");$q->execute([$projectId,trim($_POST['title']), (float)$_POST['amount'],(float)$_POST['holdback'],'pending']);}
 if($action==='accept_stage'&&$project){$q=$pdo->prepare("UPDATE acceptancestages SET status='submitted',submittedAt=CURRENT_TIMESTAMP WHERE id=? AND projectId=?");$q->execute([(int)$_POST['stage_id'],$projectId]);}
 if($action==='add_room'){$q=$pdo->prepare("INSERT INTO smetogram_rooms(user_id,project_id,name,length_m,width_m,height_m) VALUES(?,?,?,?,?,?)");$q->execute([$user['id'],$projectId?:null,trim($_POST['name'])?:'Комната',(float)$_POST['length'],(float)$_POST['width'],(float)$_POST['height']]);}
 if($action==='save_profile'){ $name=trim($_POST['name']);$email=strtolower(trim($_POST['email']));if($name!==''&&filter_var($email,FILTER_VALIDATE_EMAIL)){$q=$pdo->prepare("UPDATE users SET name=?,email=? WHERE id=?");$q->execute([$name,$email,$user['id']]);$_SESSION['user']['name']=$name;$_SESSION['user']['email']=$email;$notice='Профиль сохранён.';}}
 if($action==='import_csv'&&$project&&isset($_FILES['csv'])&&$_FILES['csv']['error']===UPLOAD_ERR_OK){$fh=fopen($_FILES['csv']['tmp_name'],'r');$header=fgetcsv($fh,0,';');if(!$header)$header=fgetcsv($fh,0,',');$map=[];foreach($header as $i=>$h)$map[mb_strtolower(trim((string)$h))]=$i;$catName=trim($_POST['category']??'Импорт из файла');$q=$pdo->prepare("INSERT INTO estimatecategories(projectId,name,sortOrder) VALUES(?,?,?)");$q->execute([$projectId,$catName,999]);$cat=(int)$pdo->lastInsertId();$count=0;while(($row=fgetcsv($fh,0,';'))!==false){if(count($row)<2)continue;$name=trim($row[$map['наименование']??0]??'');$qty=(float)str_replace(',','.',trim($row[$map['количество']??1]??'1'));$unit=trim($row[$map['ед.']??($map['единица']??2)]??'шт');$price=(float)str_replace(',','.',trim($row[$map['цена']??3]??'0'));if($name!==''){$q=$pdo->prepare("INSERT INTO estimateitems(categoryId,name,quantity,unit,price,source) VALUES(?,?,?,?,?,?)");$q->execute([$cat,$name,$qty,$unit,$price,'import']);$count++;}}fclose($fh);$notice="Импортировано позиций: $count.";}
}
$titleMap=['schedule'=>'График работ','team'=>'Команда','documents'=>'Документы','chat'=>'Чат проекта','acceptance'=>'Приёмка','billing'=>'План использования','scan'=>'Смета из файла','analytics'=>'Графики и показатели','settings'=>'Настройки','measurements'=>'Замеры'];
$pageTitle=$titleMap[$view]??'Рабочее пространство';require __DIR__.'/includes/app_header.php';
?>
<section class="page-wrap">
<div class="module-heading"><div><div class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</div><h1><?=e($pageTitle)?></h1><p class="lede"><?=e($project?($project['name'].' · '.$project['city'].' · '.$project['clientName']):'Сметограм — рабочее пространство строительного проекта.')?></p></div><div class="module-icon"><i class="bi bi-stars"></i></div></div>
<?php if($notice):?><div class="alert alert-success"><?=e($notice)?></div><?php endif;?>
<?php if($view==='schedule'):?>
<div class="module-grid"><div class="module-panel wide-panel"><div class="panel-heading"><div><h2>Этапы объекта</h2><p>Сроки и вехи оплаты по проекту.</p></div><button class="primary-button" data-bs-toggle="modal" data-bs-target="#taskModal"><i class="bi bi-plus-lg"></i> Добавить этап</button></div>
<?php if(!$project):?><div class="empty-state">Откройте проект, чтобы вести график.</div><?php else:$q=$pdo->prepare("SELECT * FROM scheduletasks WHERE projectId=? ORDER BY startsAt,id");$q->execute([$projectId]);$tasks=$q->fetchAll();foreach($tasks as $t):?><div class="timeline-row"><div class="timeline-dot <?=$t['status']==='done'?'done':''?>"><i class="bi bi-check"></i></div><div class="timeline-content"><strong><?=e($t['title'])?></strong><span><?=e($t['startsAt']?date('d.m.Y',strtotime($t['startsAt'])):'Без даты')?> — <?=e($t['endsAt']?date('d.m.Y',strtotime($t['endsAt'])):'')?></span><div class="progress-track"><span style="width:<?=$t['status']==='done'?100:($t['status']==='in_progress'?50:5)?>%"></span></div></div><b class="timeline-status"><?=e(['planned'=>'Запланировано','in_progress'=>'В работе','done'=>'Завершено','blocked'=>'Заблокировано'][$t['status']]??$t['status'])?></b></div><?php endforeach;if(!$tasks):?><div class="empty-state">Добавьте первый этап.</div><?php endif;endif;?></div><div class="module-panel"><h2>Ближайшая веха</h2><p class="panel-copy">Платёжные вехи можно привязать к этапам.</p><div class="milestone"><i class="bi bi-calendar-check"></i><div><strong>Следующий этап</strong><span>Настройте даты и сумму</span></div></div></div></div>
<?php if($project):?><div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5>Новый этап</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_task"><input class="form-control mb-3" name="title" required placeholder="Электромонтажные работы"><div class="form-grid"><input class="form-control" type="date" name="startsAt"><input class="form-control" type="date" name="endsAt"><input class="form-control" name="paymentMilestone" value="0" placeholder="Сумма этапа"></div></div><div class="modal-footer"><button class="primary-button">Добавить</button></div></form></div></div></div><?php endif;?>
<?php elseif($view==='team'):?>
<div class="module-grid"><div class="module-panel"><div class="panel-heading"><div><h2>Участники</h2><p>Роли и контакты проекта.</p></div><button class="primary-button" data-bs-toggle="modal" data-bs-target="#memberModal"><i class="bi bi-person-plus"></i> Пригласить</button></div><?php if($project){$q=$pdo->prepare("SELECT * FROM projectmembers WHERE projectId=? ORDER BY id");$q->execute([$projectId]);foreach($q->fetchAll() as $m):?><div class="member-row"><div class="member-avatar"><?=e(mb_strtoupper(mb_substr($m['role'],0,2)))?></div><div><strong><?=e($m['invitedEmail']?:$m['invitedPhone']?:'Участник')?></strong><span><?=e(['owner'=>'Владелец','foreman'=>'Прораб','contractor'=>'Бригада','designer'=>'Дизайнер','client'=>'Заказчик'][$m['role']]??$m['role'])?></span></div><em><?=e($m['joinedAt']?'Активен':'Приглашён')?></em></div><?php endforeach;endif;?></div><div class="module-panel"><h2>Права доступа</h2><div class="role-list"><p><b>Прораб</b><br><small>Смета, сроки, команда и приёмка</small></p><p><b>Бригада</b><br><small>Этапы и фото</small></p><p><b>Заказчик</b><br><small>Ход работ и приёмка</small></p></div></div></div>
<?php if($project):?><div class="modal fade" id="memberModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5>Пригласить участника</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_member"><input class="form-control mb-3" type="email" name="email" placeholder="email@example.ru"><input class="form-control mb-3" name="phone" placeholder="+7 999 000-00-00"><select class="form-select" name="role"><option value="client">Заказчик</option><option value="foreman">Прораб</option><option value="contractor">Бригада</option><option value="designer">Дизайнер</option></select></div><div class="modal-footer"><button class="primary-button">Создать приглашение</button></div></form></div></div></div><?php endif;?>
<?php elseif($view==='documents'):?>
<div class="module-panel"><div class="panel-heading"><div><h2>Документы проекта</h2><p>Договоры, счета и акты.</p></div><button class="primary-button" data-bs-toggle="modal" data-bs-target="#docModal"><i class="bi bi-plus-lg"></i> Создать документ</button></div><?php if($project){$q=$pdo->prepare("SELECT * FROM projectdocuments WHERE projectId=? ORDER BY createdAt DESC");$q->execute([$projectId]);foreach($q->fetchAll() as $d):?><div class="document-row"><div class="member-avatar"><i class="bi bi-file-earmark-text"></i></div><div><strong><?=e($d['title'])?></strong><span><?=e(mb_strtoupper($d['type']))?></span></div><em><?=e($d['status'])?></em><span><?=e($d['createdAt'])?></span></div><?php endforeach;endif;?></div>
<?php if($project):?><div class="modal fade" id="docModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5>Новый документ</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_doc"><input class="form-control mb-3" name="title" required placeholder="Договор подряда"><select class="form-select" name="type"><option value="contract">Договор</option><option value="invoice">Счёт</option><option value="act">Акт</option></select></div><div class="modal-footer"><button class="primary-button">Создать</button></div></form></div></div></div><?php endif;?>
<?php elseif($view==='chat'):?>
<div class="module-panel chat-panel"><div class="chat-tabs"><?php foreach(['foreman_client'=>'Прораб — заказчик','team'=>'Бригада','designer_client'=>'Дизайнер — заказчик','general'=>'Общий'] as $ch=>$name):?><a class="<?=$ch==='general'?'active':''?>" href="#"><?=e($name)?></a><?php endforeach;?></div><div class="chat-messages"><?php if($project){$q=$pdo->prepare("SELECT m.*,u.name FROM projectmessages m LEFT JOIN users u ON u.id=m.authorId WHERE m.projectId=? ORDER BY m.createdAt ASC");$q->execute([$projectId]);foreach($q->fetchAll() as $m):?><div class="chat-message <?=$m['authorId']===$user['id']?'mine':''?>"><div class="member-avatar"><?=e(mb_strtoupper(mb_substr($m['name']?:'Вы',0,2)))?></div><div><strong><?=e($m['name']?:'Пользователь')?></strong><p><?=nl2br(e($m['body']))?></p><small><?=e($m['createdAt'])?></small></div></div><?php endforeach;endif;?></div><?php if($project):?><form class="chat-compose" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="send_message"><input name="body" required placeholder="Напишите сообщение..."><button class="primary-button"><i class="bi bi-send"></i></button></form><?php endif;?></div>
<?php elseif($view==='acceptance'):?>
<div class="module-grid"><div class="module-panel"><div class="panel-heading"><div><h2>Этапы на приёмку</h2><p>Фиксируйте замечания и статус сдачи.</p></div><button class="primary-button" data-bs-toggle="modal" data-bs-target="#stageModal"><i class="bi bi-plus-lg"></i> Этап</button></div><?php if($project){$q=$pdo->prepare("SELECT * FROM acceptancestages WHERE projectId=? ORDER BY id DESC");$q->execute([$projectId]);foreach($q->fetchAll() as $s):?><div class="document-row"><div class="member-avatar"><i class="bi bi-check2-square"></i></div><div><strong><?=e($s['title'])?></strong><span><?=number_format((float)$s['amount'],0,',',' ')?> ₽ · удержание <?=number_format((float)$s['holdback'],0,',',' ')?> ₽</span></div><em><?=e($s['status'])?></em><?php if($s['status']==='pending'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="accept_stage"><input type="hidden" name="stage_id" value="<?=$s['id']?>"><button class="outline-button">Сдать этап</button></form><?php endif;?></div><?php endforeach;endif;?></div><div class="module-panel"><i class="bi bi-wallet2 fs-4 text-primary"></i><h2 class="mt-3">Удержание</h2><strong class="fs-4"><?=number_format((float)($project['budget']??0)*.05,0,',',' ')?> ₽</strong><p class="panel-copy">5% можно удерживать до закрытия замечаний.</p></div></div>
<?php if($project):?><div class="modal fade" id="stageModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5>Новый этап приёмки</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_stage"><input class="form-control mb-3" name="title" required placeholder="Электромонтажные работы"><div class="form-grid"><input class="form-control" name="amount" value="0" placeholder="Сумма"><input class="form-control" name="holdback" value="0" placeholder="Удержание"></div></div><div class="modal-footer"><button class="primary-button">Создать</button></div></form></div></div></div><?php endif;?>
<?php elseif($view==='scan'):?>
<div class="module-grid"><div class="module-panel upload-panel"><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="import_csv"><label class="upload-zone"><div class="upload-icon"><i class="bi bi-file-earmark-spreadsheet"></i></div><h2>Загрузите смету из CSV</h2><p>Колонки: Наименование; Количество; Ед.; Цена</p><span class="outline-button">Выбрать файл</span><input hidden type="file" name="csv" accept=".csv,.txt" required></label><?php if($project):?><div class="mt-3 d-flex gap-2"><input class="form-control" name="category" value="Импорт из файла" placeholder="Раздел"><button class="primary-button">Импортировать</button></div><?php else:?><div class="alert alert-info mt-3">Откройте проект и перейдите сюда для импорта в его смету.</div><?php endif;?></form></div><div class="module-panel"><i class="bi bi-stars fs-4 text-primary"></i><h2 class="mt-3">Смета из файла</h2><p class="panel-copy">Импорт переносит позиции в выбранный раздел и пересчитывает итог. PDF/фото можно подключить следующим этапом без изменения интерфейса.</p><div class="generated-row"><i class="bi bi-check-circle"></i> CSV / Excel-совместимый экспорт</div><div class="generated-row"><i class="bi bi-check-circle"></i> Количество, единица и цена</div><div class="generated-row"><i class="bi bi-check-circle"></i> Источник позиции сохраняется</div></div></div>
<?php elseif($view==='analytics'):?>
<?php $total=$project?0:0;if($project){$q=$pdo->prepare("SELECT COALESCE(SUM(i.quantity*i.price),0) FROM estimateitems i JOIN estimatecategories c ON c.id=i.categoryId WHERE c.projectId=?");$q->execute([$projectId]);$total=(float)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM estimateitems i JOIN estimatecategories c ON c.id=i.categoryId WHERE c.projectId=?");$q->execute([$projectId]);$count=(int)$q->fetchColumn();}?>
<div class="module-grid"><div class="module-panel"><div class="panel-heading"><div><h2>Показатели проекта</h2><p>Данные считаются напрямую из сметы.</p></div></div><div class="metric-grid"><div class="metric-card"><div><span>Стоимость</span><strong><?=number_format($total,0,',',' ')?> ₽</strong><small>текущий итог</small></div></div><div class="metric-card"><div><span>Позиции</span><strong><?=$count?></strong><small>в смете</small></div></div><div class="metric-card"><div><span>Проект</span><strong><?=e($project['status']??'—')?></strong><small>текущий статус</small></div></div></div></div><div class="metric-stack"><div class="module-panel metric-mini"><span>Контроль бюджета</span><strong>100%</strong><small>Фактические данные сметы</small></div><div class="module-panel metric-mini"><span>Последнее изменение</span><strong><?=e($project['updatedAt']??'—')?></strong><small>из базы проекта</small></div></div></div>
<?php elseif($view==='measurements'):?>
<?php $q=$pdo->prepare("SELECT * FROM smetogram_rooms WHERE user_id=? AND (project_id=? OR ?=0) ORDER BY id DESC");$q->execute([$user['id'],$projectId,$projectId]);$rooms=$q->fetchAll();?>
<div class="module-grid"><div class="module-panel"><div class="panel-heading"><div><h2>Размеры помещения</h2><p>Площадь, объём и площадь стен считаются автоматически.</p></div><button class="primary-button" data-bs-toggle="modal" data-bs-target="#roomModal"><i class="bi bi-plus-lg"></i> Добавить комнату</button></div><?php foreach($rooms as $r):$area=(float)$r['length_m']*(float)$r['width_m'];$walls=2*((float)$r['length_m']+(float)$r['width_m'])*(float)$r['height_m'];?><div class="document-row"><div class="member-avatar"><i class="bi bi-rulers"></i></div><div><strong><?=e($r['name'])?></strong><span><?=e($r['length_m'])?> × <?=e($r['width_m'])?> × <?=e($r['height_m'])?> м · стены <?=number_format($walls,1,',',' ')?> м²</span></div><em><?=number_format($area,1,',',' ')?> м²</em></div><?php endforeach;?></div><div class="module-panel"><h2>Как использовать</h2><p class="panel-copy">Сохраните размеры комнат, а затем используйте площадь и площадь стен при добавлении позиций в смету.</p></div></div>
<div class="modal fade" id="roomModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5>Новая комната</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_room"><input class="form-control mb-3" name="name" value="Комната"><div class="form-grid"><input class="form-control" name="length" value="5.2" placeholder="Длина"><input class="form-control" name="width" value="3.8" placeholder="Ширина"><input class="form-control" name="height" value="2.75" placeholder="Высота"></div></div><div class="modal-footer"><button class="primary-button">Сохранить</button></div></form></div></div></div>
<?php elseif($view==='settings'):?>
<div class="settings-layout"><div class="module-panel settings-nav"><a class="active" href="#">Профиль</a><a href="workspace.php?view=billing">Тариф и оплата</a><a href="workspace.php?view=documents">Документы</a></div><div class="module-panel"><div class="panel-heading"><div><h2>Профиль</h2><p>Данные пользователя Сметограма.</p></div></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_profile"><div class="settings-fields"><label>Имя и фамилия<input name="name" value="<?=e($user['name']??'')?>"></label><label>Email<input type="email" name="email" value="<?=e($user['email']??'')?>"></label></div><div class="d-flex justify-content-end"><button class="primary-button">Сохранить изменения</button></div></form></div></div>
<?php elseif($view==='billing'):?>
<div class="plans-grid"><?php foreach([['free','Первый проект','0 ₽','Полный проект без карты'],['project','Проект','1 490 ₽','Смета + дорожная карта + документы'],['brigade','Бригада','3 900 ₽ / мес','До 5 проектов в месяц'],['studio','Студия','7 900 ₽ / мес','Безлимит и расширенные функции']] as $p):?><div class="plan-card <?=$p[0]==='free'?'selected':''?>"><span><?=$p[1]?></span><strong><?=$p[2]?></strong><p><?=$p[3]?></p><button class="outline-button" type="button"><?=$p[0]==='free'?'Текущий план':'Выбрать план'?></button></div><?php endforeach;?></div>
<?php endif;?>
</section>
<?php require __DIR__.'/includes/app_footer.php';?>